### ISSUE TITLE
The box 'everpeace/mesos' could not be found

### ISSUE THREAD

**Issue by nlhkh** [everpeace/vagrant-mesos#45]

**Comment by everpeace** [comment]
@nlhkh Which version of vagrant did you use??
I've tested 1.6.5 and 1.7.2(latest as of 1/26/2015).  But I can't reproduce this.

**Comment by nlhkh** [comment]
I used the 1.6.5. I wonder if it has anything to do with me being outside
of the US. Other images work fine for me though.

**Comment by everpeace** [comment]
@nlhkh hmm that's weird.  Could kindly provide output of 

```
$ vagrant up --debug
```

I would be glad to help digging the issue.

**Comment by nlhkh** [comment]
Hey sorry I did not get back to you sooner. I tried it today first with --debug, and everything was working fine. I tried again without --debug, and it is all good now. I think it was the issue with Docker Hub.

Thanks!
