### ISSUE TITLE
Add a license to the repo

### ISSUE THREAD

**Issue by mbrukman** [everpeace/vagrant-mesos#46]
Could you please add an explicit LICENSE file to the repo so that it's clear under what terms you're providing this code?

Thanks!

**Comment by everpeace** [comment]
@mbrukman I added `LICENSE.txt` with MIT license.  Thanks!

**Comment by mbrukman** [comment]
That's great! Thank you, @everpeace! Much appreciated.

**Comment by everpeace** [comment]
@mbrukman I'm just curious why you care license issue. I'm really appreciated if you could tell me.  Do you have some plan to include my codes to your products/services??  If so, I'm really honored as a software engineer.

**Comment by mbrukman** [comment]
@everpeace I would like to test your code on Google Cloud Platform, and extend/update it, if necessary, to make it work well there.

If you don't include an explicit license, by convention (at least in the USA), your work is considered copyrighted with "All Rights Reserved" which means that no one can copy it or do anything else with it, without your explicit permission. Thus, I was unable to fork your repo until you added a license. (Note: I am not a lawyer, but this is my understanding of copyright.)

I also need to know what your intended license is to know whether or not I am able to contribute back to your repository. Given that you chose the MIT license, this is great and there are no further issues.

どうもありがとうございます

**Comment by everpeace** [comment]
@mbrukman Thank you for your detailed explanation.  I now understand what your intention was.  I'm not much familiar on copyright either, though, I think you're right from the point of view of the copyright.  So, now you are free to contribute back :-)  Please feel free to create issues if you found or wanted to propose any things.

**Comment by mbrukman** [comment]
BTW, here is the documentation on [copyright and licenses](https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license) from GitHub, which says essentially what I said earlier:

> **What happens if I don't choose a license?**
>
> You're under no obligation to choose a license. It's your right not to include one with your code or project, but please be aware of the implications. Generally speaking, the absence of a license means that the default copyright laws apply. This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work. This might not be what you intend.
>
> Even if this is what you intend, if you publish your source code in a public repository on GitHub, you have accepted the Terms of Service which do allow other GitHub users some rights. Specifically, you allow others to view and fork your repository.
>
> If you want to share your work with others, we strongly encourage you to include an open source license.

**Comment by everpeace** [comment]
:+1: Thanks!
