### ISSUE TITLE
launching a container through the marathon api fails 

### ISSUE THREAD

**Issue by mjvdende** [everpeace/vagrant-mesos#47]
Increase the marathon command line option --task_launch_timeout to at least the executor timeout you set on your slaves in the previous step.

**Comment by mjvdende** [comment]
marathon v0.8.0.rc2 fixes this

**Comment by everpeace** [comment]
You can just add `--task_launch_timeout 300000` to [this line in Vagrantfile](https://github.com/everpeace/vagrant-mesos/blob/master/standalone/Vagrantfile#L113).

Pre assembled jar file of v.0.8.0-RC2 has a gui issue, it missed shipping some javascripts/css assets... see mesosphere/marathon#1109 .  mesosphere/marathon#1110 will resolve the issue.

**Comment by everpeace** [comment]
I updated Marathon version to 0.8.0.  I think this has been resolved by this.
If you see some issues on this, please feel free to re-open this.
