### ISSUE TITLE
vagrant up failed. what's up, please give some help. thanks.

### ISSUE THREAD

**Issue by xiaods** [everpeace/vagrant-mesos#49]
macos 10.10

```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The '' provisioner could not be found.

Vagrant:
* Unknown configuration section 'berkshelf'.
* Unknown configuration section 'omnibus'.
```

**Comment by everpeace** [comment]
@xiaods Thanks for trying the project!  

I've faced this problem before.  At that time, I versionup-ed vagrant to the latest and  I cleanup-ed several caches, those are `~/.vagrant`, `~/.berkshelf` and `./vagrant`.  And then I re-installed vagrant plugins.  This worked for me at that time.  I hope this will help you.

**Comment by everpeace** [comment]
@xiaods Or, you missed some plugins required.  Please check all required plugins installed.

**Comment by xiaods** [comment]
@everpeace yes, it works like a charm. thanks a lot.
