### ISSUE TITLE
vagrant up currently failing

### ISSUE THREAD

**Issue by jsindy** [everpeace/vagrant-mesos#56]
cd multinodes/
vagrant up

"here are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The '' provisioner could not be found.

Vagrant:
* Unknown configuration section 'berkshelf'.
* Unknown configuration section 'omnibus'.

"

**Comment by everpeace** [comment]
Did you confirm that you did install all required vagrant plugins??
If so, please tell me which version of vagrant you are using.

**Comment by goodgoblin** [comment]
I got the exact same error initially, and it went away after I installed the vagrant plugins and ChefDK.

**Comment by jomach** [comment]
Same problem here..

**Comment by jsindy** [comment]
Yeah it was a plugins issue.
