### ISSUE TITLE
failed during "vagrant up" 

### ISSUE THREAD

**Issue by meirwah** [everpeace/vagrant-mesos#60]
Getting this error:

Fetching 'mesos' from git://github.com/everpeace/cookbook-mesos.git (at master)
Fetching cookbook index from https://supermarket.getchef.com...
Error retrieving universe from source: https://supermarket.getchef.com
  * [Berkshelf::APIClient::TimeoutError] Unable to connect to: https://supermarket.getchef.com

    stderr: Required artifacts do not exist at the desired version
Missing artifacts: apt
Unable to find a solution for demands: apt (>= 0.0.0), docker (0.37.0), mesos (0.2.2)

**Comment by everpeace** [comment]
Direct cause is "Unable to connect to: https://supermarket.getchef.com" as your output said.
However "https://supermarket.getchef.com" doesn't seem to be down.
Please check your network configuration.

**Comment by everpeace** [comment]
@meirwah Do you still have this problem??  Would you mind closing this issue?
