### ISSUE TITLE
multinodes vagrant up

### ISSUE THREAD

**Issue by thorduri** [everpeace/vagrant-mesos#64]
Due to the vagrant-berkshelf plugin changing into a middleware (I'm not exactly sure when/how this happened or what the full implications are, apologies for this) it seems it's now a requirement to run
`vagrant up --provision` to have everything done for you.

Simply running `vagrant up` will bomb out with a confusing error message regarding Berkshelf.

I'm not 100% this is a problem for everyone, as it seem to depend on the versions of the software being used, in my case: OSX, Vagrant 1.7.2, ChefDK 0.6.0, vagrant-berkshelf (4.0.4), vagrant-omnibus (1.4.1).

The ,,fix'' if you will would be to change the README example from `vagrant up` to `vagrant up --provision`.

**Comment by everpeace** [comment]
could you post the log for me to dig what happened??

**Comment by thorduri** [comment]
This was a PEBKAC.  Apologies!
