### ISSUE TITLE
standalone does not seem to work in 

### ISSUE THREAD

**Issue by sqorbrody** [everpeace/vagrant-mesos#70]
Cloned the repo, used a pretty stand gemset but not able to run vagrant up?

SQOR-0089:standalone brody$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The '' provisioner could not be found.

Vagrant:
* Unknown configuration section 'berkshelf'.
* Unknown configuration section 'omnibus'.

SQOR-0089:standalone brody$ 

???

....

SQOR-0089:standalone brody$ gem list 

*** LOCAL GEMS ***

addressable (2.3.8)
akami (1.3.1)
ast (2.0.0)
astrolabe (1.3.0)
aws-sdk (2.1.4)
aws-sdk-core (2.1.4)
aws-sdk-resources (2.1.4)
berkshelf (3.3.0)
berkshelf-api-client (1.3.0)
bigdecimal (1.2.6)
buff-config (1.0.1)
buff-extensions (1.0.0)
buff-ignore (1.1.1)
buff-ruby_engine (0.1.0)
buff-shell_out (0.2.0)
builder (3.2.2)
bundler (1.10.5)
bundler-unload (1.0.2)
celluloid (0.16.0)
celluloid-io (0.16.2)
chef (12.4.1)
chef-config (12.4.1)
chef-zero (4.2.3)
chefspec (4.2.0)
cleanroom (1.0.0)
coderay (1.1.0)
dep-selector-libgecode (1.0.2)
dep_selector (1.0.3)
diff-lcs (1.2.5)
em-winrm (0.6.0)
erubis (2.7.0)
eventmachine (1.0.7)
excon (0.45.3)
executable-hooks (1.3.2)
faraday (0.9.1)
fauxhai (2.3.0)
ffi (1.9.10)
ffi-yajl (2.2.0)
fog (1.23.0)
fog-brightbox (0.7.2)
fog-core (1.32.0)
fog-json (1.0.2)
fog-softlayer (0.4.7)
foodcritic (4.0.0)
formatador (0.2.5)
gem-wrappers (1.2.7)
gherkin (2.12.2)
gssapi (1.0.3)
gyoku (1.3.1)
hashie (2.1.2)
highline (1.7.2)
hitimes (1.2.2)
httpclient (2.6.0.1)
httpi (0.9.7)
inflecto (0.0.2)
io-console (0.4.3)
ipaddress (0.8.0)
jmespath (1.0.2)
json (1.8.3, 1.8.1)
kitchen-ec2 (0.10.0)
kitchen-vagrant (0.18.0)
knife-ec2 (0.10.0)
knife-windows (0.8.5)
libyajl2 (1.2.0)
little-plugger (1.1.3)
logging (1.8.2)
method_source (0.8.2)
mime-types (2.6.1)
mini_portile (0.6.2)
minitar (0.5.4)
mixlib-authentication (1.3.0)
mixlib-cli (1.5.0)
mixlib-config (2.2.1)
mixlib-log (1.6.0)
mixlib-shellout (2.1.0)
multi_json (1.11.2)
multipart-post (2.0.0)
net-http-persistent (2.9.4)
net-scp (1.2.1)
net-ssh (2.9.2)
net-ssh-gateway (1.2.0)
net-ssh-multi (1.2.1)
net-telnet (0.1.1)
nio4r (1.1.0)
nokogiri (1.6.6.2)
nori (1.1.5)
octokit (3.8.0)
ohai (8.5.0)
parser (2.2.2.6)
plist (3.1.0)
polyglot (0.3.5)
powerpack (0.1.1)
pry (0.10.1)
psych (2.0.8)
rack (1.6.4)
rainbow (2.0.0)
rake (10.4.2)
rdoc (4.2.0)
retryable (2.0.1)
ridley (4.2.0)
rspec (3.3.0)
rspec-core (3.3.1)
rspec-expectations (3.3.0)
rspec-its (1.2.0)
rspec-mocks (3.3.1)
rspec-support (3.3.0)
rspec_junit_formatter (0.2.3)
rubocop (0.32.1)
ruby-progressbar (1.7.5)
rubygems-bundler (1.4.4)
rubyntlm (0.1.1)
rufus-lru (1.0.5)
rvm (1.11.3.9)
safe_yaml (1.0.4)
savon (0.9.5)
sawyer (0.6.0)
semverse (1.2.1)
serverspec (2.19.0)
sfl (2.2)
slop (3.6.0)
solve (1.2.1)
specinfra (2.37.1)
syslog-logger (1.6.8)
systemu (2.6.5)
test-kitchen (1.4.1)
thor (0.19.1)
timers (4.0.1)
treetop (1.6.3)
uuidtools (2.1.5)
varia_model (0.4.0)
wasabi (1.0.0)
winrm (1.2.0)
winrm-s (0.2.4)
wmi-lite (1.0.0)
yajl-ruby (1.2.1)

...

SQOR-0089:standalone brody$ vagrant --version
Vagrant 1.7.2
SQOR-0089:standalone brody$ vagrant plugin list
vagrant-share (1.1.3, system)
SQOR-0089:standalone brody$

**Comment by jonasrosland** [comment]
I got the exact same error earlier today.
Installing the berkshelf and omnibus plugins solved it:
```
vagrant plugin install vagrant-berkshelf
vagrant plugin install vagrant-omnibus
```

Also make sure you have ChefDK installed:
```
brew cask install Caskroom/cask/chefdk
```

Perhaps add this to the docs?

**Comment by everpeace** [comment]
I think I wrote prerequisites explicitly. Please read [here](https://github.com/everpeace/vagrant-mesos#prerequisites)
